### ISSUE TITLE
passing custom reporter to test class

### ISSUE THREAD

**Issue by anktrj** [mario-galic/scalatest-custom-reporter-example#1]
How to pass the custom reporter to the test class? I am using Intellij IDEA.

I can't find anything similar on the internet.

I don't want to write `testSuite.run(Some(test), Args(reporter))` in every test class.

Thankyou!

**Comment by ankiiitraj** [comment]
I was able to run it, earlier doing a silly mistake!

Now, getting some errors looks like IntelliJ is getting angry!

can someone confirm it is intellij error
`Reporter completed abruptly with an exception after receiving event: TestStarting(...)
	at com.intuit.etlmockit.utils.CustomReporter.apply(CustomReporter.scala:9)
	at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10(DispatchReporter.scala:249)
	at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10$adapted(DispatchReporter.scala:248)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at org.scalatest.DispatchReporter$Propagator.run(DispatchReporter.scala:248)
	at java.lang.Thread.run(Thread.java:750)
`

**Comment by anktrj** [comment]
I was able to run it, earlier doing a silly mistake!

Now, getting some errors, pasted below 👇
```
Reporter completed abruptly with an exception after receiving event: TestStarting(...).
scala.MatchError: TestStarting(...) (of class org.scalatest.events.TestStarting)
	at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10(DispatchReporter.scala:249)
	at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10$adapted(DispatchReporter.scala:248)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at org.scalatest.DispatchReporter$Propagator.run(DispatchReporter.scala:248)
	at java.lang.Thread.run(Thread.java:750)
Reporter completed abruptly with an exception after receiving event: TestSucceeded(...).
java.lang.IllegalArgumentException: fromIndex(0) > toIndex(-1)
	at java.util.ArrayList.subListRangeCheck(ArrayList.java:1016)
	at java.util.ArrayList$SubList.subList(ArrayList.java:1221)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.treeBuilder.ParallelTreeBuilder.getSuite(ParallelTreeBuilder.java:198)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.treeBuilder.ParallelTreeBuilder.closeScope(ParallelTreeBuilder.java:217)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestReporterWithLocation.apply(ScalaTestReporterWithLocation.java:96)
	at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10(DispatchReporter.scala:249)
	at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10$adapted(DispatchReporter.scala:248)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at org.scalatest.DispatchReporter$Propagator.run(DispatchReporter.scala:248)
	at java.lang.Thread.run(Thread.java:750)
```

PS: on proper implementation of custom reporter it was not throwing errors!

Thanks for creating this example!

**Comment by anktrj** [comment]
Hi @mariogalic, How to pass custom reporter via POM file?
